import { PayerConfig } from '@/types/payer'

export const aetnaTexasConfig: PayerConfig = {
  id: 'aetna-texas',
  name: 'Aetna Better Health TX',
  full_name: 'Aetna Better Health of Texas Medicaid',
  state: 'TX',
  fax_numbers: {
    primary: '865-452-9888',
    appeals: '865-452-9889',
  },
  portal_url: 'https://www.aetnabetterhealth.com/texas',
  submission_methods: ['fax', 'portal'],
  response_deadline_standard_days: 7,
  response_deadline_urgent_hours: 72,
  notes: 'Aetna Better Health of Texas requires standard STAR+PLUS documentation including OASIS assessment, physician orders, and NPI validation.',
  required_form_fields: [
    {
      field_id: 'member_name',
      label: 'Member Full Name',
      required: true,
      type: 'text',
      hipaa_phi: true,
      extraction_hint: 'Extract member full name from Aetna clinical documentation.',
    },
    {
      field_id: 'medicaid_id',
      label: 'Medicaid Member ID',
      required: true,
      type: 'text',
      validation_regex: '^[0-9]{9,10}$',
      hipaa_phi: true,
      extraction_hint: 'Extract 9 or 10-digit Aetna Medicaid member ID.',
    },
    {
      field_id: 'dob',
      label: 'Date of Birth',
      required: true,
      type: 'date',
      hipaa_phi: true,
      extraction_hint: 'Extract patient date of birth (MM/DD/YYYY).',
    },
    {
      field_id: 'primary_icd10',
      label: 'Primary ICD-10 Code',
      required: true,
      type: 'icd10',
      hipaa_phi: true,
      extraction_hint: 'Extract primary diagnosis code for requested services.',
    },
    {
      field_id: 'requesting_npi',
      label: 'Requesting Provider NPI',
      required: true,
      type: 'npi',
      validation_regex: '^[0-9]{10}$',
      hipaa_phi: false,
      extraction_hint: 'Extract 10-digit requesting provider NPI.',
    },
    {
      field_id: 'service_type',
      label: 'Service Type Requested',
      required: true,
      type: 'select',
      options: ['Personal Attendant Services', 'Community Care Services', 'Nursing Care'],
      hipaa_phi: false,
      extraction_hint: 'Extract requested service category.',
    },
    {
      field_id: 'requested_hours_per_week',
      label: 'Requested Hours Per Week',
      required: true,
      type: 'text',
      hipaa_phi: false,
      extraction_hint: 'Extract requested weekly service hours.',
    },
    {
      field_id: 'physician_signature_date',
      label: 'Physician Signature Date',
      required: true,
      type: 'date',
      hipaa_phi: true,
      extraction_hint: 'Extract physician signature date on treatment plan.',
    },
  ],
  clinical_criteria: [
    {
      criterion_id: 'AETNA_MED_NEC',
      name: 'Aetna Medical Necessity Criteria',
      description: 'Documented functional impairment requiring attendant assistance for daily living activities.',
      required: true,
      documentation_required: ['Physician Orders', 'OASIS Assessment'],
    },
  ],
  denial_codes: {
    ET01: {
      code: 'ET01',
      reason: 'Missing clinical documentation',
      appeal_strategy: 'Submit complete clinical chart notes, physician orders, and OASIS scoring.',
      typical_overturn_rate: 0.81,
    },
    ET02: {
      code: 'ET02',
      reason: 'Level of care non-qualifying',
      appeal_strategy: 'Provide Form 2401 nursing facility level of care evaluation and physician attestation.',
      typical_overturn_rate: 0.67,
    },
    ET03: {
      code: 'ET03',
      reason: 'Untimely filing',
      appeal_strategy: 'Include proof of timely initial submission fax confirmation or portal receipt.',
      typical_overturn_rate: 0.70,
    },
  },
}
