import { PayerConfig } from '@/types/payer'

export const humanaTexasConfig: PayerConfig = {
  id: 'humana-texas',
  name: 'Humana Healthy Horizons TX',
  full_name: 'Humana Healthy Horizons in Texas Medicaid',
  state: 'TX',
  fax_numbers: {
    primary: '800-459-3354',
    appeals: '800-459-3355',
  },
  portal_url: 'https://www.humana.com/provider',
  submission_methods: ['fax', 'portal'],
  response_deadline_standard_days: 7,
  response_deadline_urgent_hours: 72,
  notes: 'Humana Healthy Horizons Texas requires prior authorization for all personal attendant and community care services.',
  required_form_fields: [
    {
      field_id: 'member_name',
      label: 'Member Full Name',
      required: true,
      type: 'text',
      hipaa_phi: true,
      extraction_hint: 'Extract member full legal name.',
    },
    {
      field_id: 'medicaid_id',
      label: 'Medicaid Member ID',
      required: true,
      type: 'text',
      validation_regex: '^[0-9]{9,10}$',
      hipaa_phi: true,
      extraction_hint: 'Extract 9 or 10-digit Humana Medicaid member ID.',
    },
    {
      field_id: 'dob',
      label: 'Date of Birth',
      required: true,
      type: 'date',
      hipaa_phi: true,
      extraction_hint: 'Extract patient DOB.',
    },
    {
      field_id: 'primary_icd10',
      label: 'Primary ICD-10 Code',
      required: true,
      type: 'icd10',
      hipaa_phi: true,
      extraction_hint: 'Extract primary diagnosis code.',
    },
    {
      field_id: 'requesting_npi',
      label: 'Requesting Provider NPI',
      required: true,
      type: 'npi',
      validation_regex: '^[0-9]{10}$',
      hipaa_phi: false,
      extraction_hint: 'Extract 10-digit NPI.',
    },
    {
      field_id: 'service_type',
      label: 'Service Type Requested',
      required: true,
      type: 'select',
      options: ['Personal Attendant Services', 'Community Care Services'],
      hipaa_phi: false,
      extraction_hint: 'Extract requested service category.',
    },
    {
      field_id: 'requested_hours_per_week',
      label: 'Requested Hours Per Week',
      required: true,
      type: 'text',
      hipaa_phi: false,
      extraction_hint: 'Extract requested weekly hours.',
    },
    {
      field_id: 'physician_signature_date',
      label: 'Physician Signature Date',
      required: true,
      type: 'date',
      hipaa_phi: true,
      extraction_hint: 'Extract physician signature date on Plan of Care.',
    },
  ],
  clinical_criteria: [
    {
      criterion_id: 'HUMANA_MED_NEC',
      name: 'Humana Medical Necessity',
      description: 'Documented medical necessity for attendant care services.',
      required: true,
      documentation_required: ['Plan of Care Form 485', 'Physician Notes'],
    },
  ],
  denial_codes: {
    H001: {
      code: 'H001',
      reason: 'Clinical information incomplete',
      appeal_strategy: 'Provide complete Form 485, OASIS summary, and physician clinical notes.',
      typical_overturn_rate: 0.79,
    },
    H002: {
      code: 'H002',
      reason: 'Benefit maximum reached',
      appeal_strategy: 'Submit medical necessity override letter from ordering physician.',
      typical_overturn_rate: 0.62,
    },
  },
}
