import { PayerConfig } from '@/types/payer'

export const molinaTexasConfig: PayerConfig = {
  id: 'molina-texas',
  name: 'Molina Healthcare TX',
  full_name: 'Molina Healthcare of Texas Medicaid',
  state: 'TX',
  fax_numbers: {
    primary: '866-420-3639',
    appeals: '866-420-3640',
  },
  portal_url: 'https://provider.molinahealthcare.com',
  submission_methods: ['fax', 'portal'],
  response_deadline_standard_days: 7,
  response_deadline_urgent_hours: 72,
  notes: 'Molina Texas Medicaid requires strict ADL evaluation scores and signed Form 485 for Personal Attendant Services.',
  required_form_fields: [
    {
      field_id: 'member_name',
      label: 'Member Full Name',
      required: true,
      type: 'text',
      hipaa_phi: true,
      extraction_hint: 'Extract member full name from Molina authorization form.',
    },
    {
      field_id: 'medicaid_id',
      label: 'Medicaid Member ID',
      required: true,
      type: 'text',
      validation_regex: '^[0-9]{9,10}$',
      hipaa_phi: true,
      extraction_hint: 'Extract 9 or 10-digit Molina Medicaid ID.',
    },
    {
      field_id: 'dob',
      label: 'Date of Birth',
      required: true,
      type: 'date',
      hipaa_phi: true,
      extraction_hint: 'Extract patient DOB (MM/DD/YYYY).',
    },
    {
      field_id: 'primary_icd10',
      label: 'Primary ICD-10 Code',
      required: true,
      type: 'icd10',
      hipaa_phi: true,
      extraction_hint: 'Extract primary diagnosis code.',
    },
    {
      field_id: 'requesting_npi',
      label: 'Requesting NPI',
      required: true,
      type: 'npi',
      validation_regex: '^[0-9]{10}$',
      hipaa_phi: false,
      extraction_hint: 'Extract requesting provider NPI.',
    },
    {
      field_id: 'service_type',
      label: 'Service Type',
      required: true,
      type: 'select',
      options: ['Attendant Care', 'Respite Care', 'Nursing Supervision'],
      hipaa_phi: false,
      extraction_hint: 'Extract requested Molina service category.',
    },
    {
      field_id: 'requested_hours_per_week',
      label: 'Requested Weekly Hours',
      required: true,
      type: 'text',
      hipaa_phi: false,
      extraction_hint: 'Extract total requested attendant hours per week.',
    },
    {
      field_id: 'physician_signature_date',
      label: 'Physician Signature Date',
      required: true,
      type: 'date',
      hipaa_phi: true,
      extraction_hint: 'Extract physician signature date on Plan of Care.',
    },
  ],
  clinical_criteria: [
    {
      criterion_id: 'MOLINA_ADL_DEFICIT',
      name: 'Molina ADL Assistance Criteria',
      description: 'Documented deficit in at least two Activities of Daily Living (ADLs).',
      required: true,
      documentation_required: ['OASIS Functional Assessment', 'Clinical Evaluation'],
    },
  ],
  denial_codes: {
    M001: {
      code: 'M001',
      reason: 'Lack of clinical necessity documentation',
      appeal_strategy: 'Provide detailed ADL task scoring matrix and physician attestation of physical limitations.',
      typical_overturn_rate: 0.76,
    },
    M002: {
      code: 'M002',
      reason: 'Incomplete prior authorization request form',
      appeal_strategy: 'Resubmit fully populated Molina PA form with all member and provider NPI fields filled.',
      typical_overturn_rate: 0.88,
    },
    M003: {
      code: 'M003',
      reason: 'Non-covered benefit level',
      appeal_strategy: 'Submit evidence of STAR+PLUS HCBS waiver enrollment and LOC approval.',
      typical_overturn_rate: 0.60,
    },
  },
}
