import { PayerConfig } from '@/types/payer'

export const starPlusConfig: PayerConfig = {
  id: 'star-plus',
  name: 'Texas STAR+PLUS',
  full_name: 'Texas STAR+PLUS Medicaid Managed Care Program',
  state: 'TX',
  fax_numbers: {
    primary: '800-252-8263',
    appeals: '800-252-8264',
  },
  portal_url: 'https://www.tmhp.com',
  submission_methods: ['fax', 'portal'],
  response_deadline_standard_days: 7,
  response_deadline_urgent_hours: 72,
  notes: 'Texas STAR+PLUS HCBS prior authorization requires Nursing Facility Level of Care determination, completed OASIS, and physician-signed Plan of Care within 60 days.',
  required_form_fields: [
    {
      field_id: 'member_name',
      label: 'Member Full Name',
      required: true,
      type: 'text',
      hipaa_phi: true,
      extraction_hint: 'Extract member or patient full legal name from clinical notes or OASIS header.',
    },
    {
      field_id: 'medicaid_id',
      label: 'Medicaid Member ID',
      required: true,
      type: 'text',
      validation_regex: '^[0-9]{9,10}$',
      hipaa_phi: true,
      extraction_hint: 'Extract 9 or 10-digit Texas Medicaid ID / State ID number.',
    },
    {
      field_id: 'dob',
      label: 'Date of Birth',
      required: true,
      type: 'date',
      hipaa_phi: true,
      extraction_hint: 'Extract patient date of birth in MM/DD/YYYY format.',
    },
    {
      field_id: 'primary_icd10',
      label: 'Primary ICD-10 Diagnosis Codes',
      required: true,
      type: 'icd10',
      hipaa_phi: true,
      extraction_hint: 'Extract primary and secondary ICD-10 diagnosis codes (up to 5 codes) supporting home care need.',
    },
    {
      field_id: 'requesting_npi',
      label: 'Requesting Provider NPI',
      required: true,
      type: 'npi',
      validation_regex: '^[0-9]{10}$',
      hipaa_phi: false,
      extraction_hint: 'Extract 10-digit National Provider Identifier (NPI) of requesting agency or ordering physician.',
    },
    {
      field_id: 'requesting_provider_name',
      label: 'Requesting Provider Name',
      required: true,
      type: 'text',
      hipaa_phi: false,
      extraction_hint: 'Extract requesting home care agency name or physician full name.',
    },
    {
      field_id: 'servicing_npi',
      label: 'Servicing Provider NPI',
      required: false,
      type: 'npi',
      validation_regex: '^[0-9]{10}$',
      hipaa_phi: false,
      extraction_hint: 'Extract servicing provider NPI if different from requesting provider.',
    },
    {
      field_id: 'service_type',
      label: 'Requested Service Type',
      required: true,
      type: 'select',
      options: [
        'Personal Attendant Services (PAS)',
        'Community Attendant Services (CAS)',
        'Day Activity & Health Services (DAHS)',
        'Supported Employment',
      ],
      hipaa_phi: false,
      extraction_hint: 'Extract specific HCBS service type requested (e.g. PAS, CAS, DAHS).',
    },
    {
      field_id: 'requested_hours_per_week',
      label: 'Requested Units / Hours Per Week',
      required: true,
      type: 'text',
      hipaa_phi: false,
      extraction_hint: 'Extract recommended or prescribed personal attendant hours per week.',
    },
    {
      field_id: 'start_date',
      label: 'Requested Start Date',
      required: true,
      type: 'date',
      hipaa_phi: false,
      extraction_hint: 'Extract requested prior authorization effective start date.',
    },
    {
      field_id: 'end_date',
      label: 'Requested End Date',
      required: true,
      type: 'date',
      hipaa_phi: false,
      extraction_hint: 'Extract requested prior authorization end date (usually 12 months after start date).',
    },
    {
      field_id: 'medical_necessity_justification',
      label: 'Medical Necessity Justification',
      required: true,
      type: 'textarea',
      hipaa_phi: true,
      extraction_hint: 'Extract clinical narrative demonstrating member functional limitations, ADL/IADL assistance needs, and medical necessity (minimum 500 characters).',
    },
    {
      field_id: 'loc_attached',
      label: 'Level of Care (LOC) Determination Attached',
      required: true,
      type: 'boolean',
      hipaa_phi: false,
      extraction_hint: 'Verify if Nursing Facility Level of Care (LOC) assessment is attached.',
    },
    {
      field_id: 'oasis_date',
      label: 'OASIS Assessment Date',
      required: true,
      type: 'date',
      hipaa_phi: true,
      extraction_hint: 'Extract completion date of the most recent OASIS assessment.',
    },
    {
      field_id: 'homebound_documented',
      label: 'Homebound Status Documented',
      required: true,
      type: 'boolean',
      hipaa_phi: true,
      extraction_hint: 'Verify whether patient homebound status and qualifying reasons are documented.',
    },
    {
      field_id: 'physician_signature_date',
      label: 'Physician Signature Date on Plan of Care',
      required: true,
      type: 'date',
      hipaa_phi: true,
      extraction_hint: 'Extract date physician signed Form 485 / Plan of Care (must be within 60 days).',
    },
  ],
  clinical_criteria: [
    {
      criterion_id: 'LOC_NF',
      name: 'Nursing Facility Level of Care',
      description: 'Member must meet Level of Care (LOC) criteria for nursing facility admission.',
      required: true,
      documentation_required: ['OASIS Assessment', 'Medical Needs Assessment Form 2401'],
    },
    {
      criterion_id: 'COMMUNITY_SAFETY',
      name: 'Community Safety Assessment',
      description: 'Member must be able to safely receive services in a community home setting with attendant support.',
      required: true,
      documentation_required: ['Community Safety Evaluation', 'Care Plan Risk Assessment'],
    },
    {
      criterion_id: 'MEDICAL_NECESSITY',
      name: 'Medical Necessity & Non-Duplication',
      description: 'Services must be medically necessary to assist with ADLs/IADLs and not duplicate other Medicaid programs.',
      required: true,
      documentation_required: ['Physician Orders', 'Clinical Progress Notes'],
    },
    {
      criterion_id: 'SIGNED_POC',
      name: 'Signed Plan of Care (Form 485)',
      description: 'Plan of Care must be signed and dated by ordering physician within 60 days of authorization request.',
      required: true,
      documentation_required: ['CMS-485 Plan of Care', 'Physician Signature Page'],
    },
    {
      criterion_id: 'FACE_TO_FACE',
      name: 'Face-to-Face Encounter',
      description: 'Face-to-face clinical encounter related to primary diagnosis documented within 90 days of start date.',
      required: true,
      documentation_required: ['Physician Visit Note', 'Hospital Discharge Summary'],
    },
  ],
  denial_codes: {
    A001: {
      code: 'A001',
      reason: 'Not medically necessary',
      appeal_strategy: 'Provide detailed ADL/IADL scoring from OASIS, physician letter emphasizing functional decline without attendant care, and 30-day care logs.',
      typical_overturn_rate: 0.72,
    },
    A002: {
      code: 'A002',
      reason: 'Insufficient clinical documentation',
      appeal_strategy: 'Attach signed Form 485, complete OASIS documentation, physician face-to-face encounter note, and daily care task breakdown.',
      typical_overturn_rate: 0.85,
    },
    A003: {
      code: 'A003',
      reason: 'Level of Care (LOC) criteria not met',
      appeal_strategy: 'Submit updated Form 2401, physician statement on skilled nursing/attendant necessity, and cognitive/mobility impairment documentation.',
      typical_overturn_rate: 0.64,
    },
    A004: {
      code: 'A004',
      reason: 'Duplicate service requested',
      appeal_strategy: 'Clarify distinct service hours, show non-overlapping schedules with adult day care or family care, and submit weekly schedule matrix.',
      typical_overturn_rate: 0.78,
    },
    A005: {
      code: 'A005',
      reason: 'Provider not enrolled in STAR+PLUS network',
      appeal_strategy: 'Include Medicaid NPI confirmation letter, active STAR+PLUS contract page, and request single-case agreement if out-of-network continuity of care applies.',
      typical_overturn_rate: 0.55,
    },
  },
}
