import { PayerConfig } from '@/types/payer'

export const uhcTexasConfig: PayerConfig = {
  id: 'uhc-texas',
  name: 'UHC Community Plan TX',
  full_name: 'UnitedHealthcare Community Plan of Texas Medicaid',
  state: 'TX',
  fax_numbers: {
    primary: '888-940-1170',
    appeals: '888-940-1171',
  },
  portal_url: 'https://www.uhcprovider.com',
  submission_methods: ['fax', 'portal'],
  response_deadline_standard_days: 7,
  response_deadline_urgent_hours: 72,
  notes: 'UnitedHealthcare Texas requires online portal submission via UHCProvider portal or designated fax line. Primary ICD-10 diagnosis and signed Plan of Care required.',
  required_form_fields: [
    {
      field_id: 'member_name',
      label: 'Member Full Name',
      required: true,
      type: 'text',
      hipaa_phi: true,
      extraction_hint: 'Extract member full legal name from clinical notes or UHC card.',
    },
    {
      field_id: 'medicaid_id',
      label: 'Medicaid / UHC Member ID',
      required: true,
      type: 'text',
      validation_regex: '^[0-9]{9,11}$',
      hipaa_phi: true,
      extraction_hint: 'Extract 9 to 11 digit UHC Medicaid member ID number.',
    },
    {
      field_id: 'dob',
      label: 'Date of Birth',
      required: true,
      type: 'date',
      hipaa_phi: true,
      extraction_hint: 'Extract patient date of birth (MM/DD/YYYY).',
    },
    {
      field_id: 'primary_icd10',
      label: 'Primary ICD-10 Code',
      required: true,
      type: 'icd10',
      hipaa_phi: true,
      extraction_hint: 'Extract primary ICD-10 code for requested services.',
    },
    {
      field_id: 'requesting_npi',
      label: 'Requesting Provider NPI',
      required: true,
      type: 'npi',
      validation_regex: '^[0-9]{10}$',
      hipaa_phi: false,
      extraction_hint: 'Extract 10-digit requesting provider NPI.',
    },
    {
      field_id: 'service_type',
      label: 'Service Type Requested',
      required: true,
      type: 'select',
      options: ['Personal Care Services (PCS)', 'Private Duty Nursing (PDN)', 'Home Health Aide'],
      hipaa_phi: false,
      extraction_hint: 'Extract requested home care service classification.',
    },
    {
      field_id: 'requested_hours_per_week',
      label: 'Requested Hours Per Week',
      required: true,
      type: 'text',
      hipaa_phi: false,
      extraction_hint: 'Extract requested attendant hours per week.',
    },
    {
      field_id: 'physician_signature_date',
      label: 'Physician Signature Date',
      required: true,
      type: 'date',
      hipaa_phi: true,
      extraction_hint: 'Extract date physician signed treatment plan.',
    },
  ],
  clinical_criteria: [
    {
      criterion_id: 'UHC_MED_NEC',
      name: 'UHC Medical Necessity Guidelines',
      description: 'Patient must require physical assistance with 2+ ADLs due to chronic illness or disability.',
      required: true,
      documentation_required: ['Functional Assessment', 'Physician Order'],
    },
    {
      criterion_id: 'UHC_POC',
      name: 'Signed Treatment Plan',
      description: 'Active Plan of Care signed within 60 days of prior authorization submission.',
      required: true,
      documentation_required: ['Plan of Care Form 485'],
    },
  ],
  denial_codes: {
    U001: {
      code: 'U001',
      reason: 'Insufficient clinical documentation',
      appeal_strategy: 'Submit complete UHC prior authorization form, functional assessment scores, and recent clinical visit notes.',
      typical_overturn_rate: 0.80,
    },
    U002: {
      code: 'U002',
      reason: 'Prior authorization required before service rendering',
      appeal_strategy: 'Provide evidence of retroactive authorization eligibility or emergency start date rationale.',
      typical_overturn_rate: 0.50,
    },
    U003: {
      code: 'U003',
      reason: 'Requested service units exceed benefit limit',
      appeal_strategy: 'Submit physician letter of medical necessity for additional hours above standard cap.',
      typical_overturn_rate: 0.65,
    },
  },
}
